
-- File: PUI_UF_CastBar_Defaults.lua
-- Purpose: Castbar defaults only.


local ADDON_NAME, ns = ...


local CastBar = ns.Modules.CastBar

local COLORS = {
  player = { 1.0, 0.7, 0.0, 1.0 },
  pet = { 0.7, 0.9, 1.0, 1.0 },
  target = { 0.2, 0.8, 1.0, 1.0 },
  focus = { 0.6, 1.0, 0.4, 1.0 },
  boss = { 1.0, 0.6, 0.2, 1.0 },
  bg = { 0.08, 0.08, 0.08, 0.40 },
  uninterruptible = { 0.7, 0.7, 0.7, 1.0 },
}

local defaults = {
  profile = {
    enabled = true,

    player = {
      enabled = true,
      width = 400,
      height = 24,
      showIcon = true,
      point = "BOTTOM",
      relativePoint = "TOP",
      relativeTo = "PUI_PRD_Frame",
      offsetX = 0,
      offsetY = 6,
      userMoved = false,
      texture = "Pleebar",
      useClassColor = false,
      color = COLORS.player,
      bgColor = COLORS.bg,

      showTotal = true,
      showPingOverlay = true,
      showEmpowerPips = true,
      showSpark = true,
      reverseFill = false,
      timeToHold = 0.20,
      showChannelTicks = true,
      channelTickThickness = 2,
      showDelayText = true,
      displayTarget = false,
      showDisintegrateClipWarning = false,
      disintegrateClipWarningText = "DON'T CLIP",
      borderSize = 1,
      showInstantCasts = true,
      instantCastFillMode = "DRAIN",
      instantCastAlpha = 0.65,
      instantCastTexture = "Pleebar",
      instantCastUseOverlay = true,
      instantCastOverlayTexture = "PUI Stripes",
      instantCastOverlayAlpha = 0.35,
      showEmpowerHold = true,

      empowerSegmentColors = {
        { 1.00, 0.90, 0.30, 1.0 },
        { 1.00, 0.70, 0.10, 1.0 },
        { 0.90, 0.40, 0.10, 1.0 },
        { 0.90, 0.15, 0.15, 1.0 },
      },
      empowerHoldColor = { 1.00, 1.00, 1.00, 1.0 },

      text = {
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "LEFT",
        offX = 6,
        offY = 0,
      },
      timeText = {
        showCast = true,
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "RIGHT",
        offX = -6,
        offY = 0,
      },
    },

    pet = {
      enabled = true,
      width = 180,
      height = 16,
      showIcon = true,
      borderSize = 1,
      attachToUF = true,
      point = "TOP",
      relativePoint = "BOTTOM",
      relativeTo = "PleebUI_UnitFrame_pet",
      offsetX = 0,
      offsetY = -6,
      userMoved = false,
      texture = "Pleebar",
      useClassColor = false,
      color = COLORS.pet,
      bgColor = COLORS.bg,
      showTotal = true,
      showSpark = true,
      reverseFill = false,
      timeToHold = 0.20,
      showDelayText = true,
      displayTarget = false,
      uninterruptShieldMode = "LEFT",
      uninterruptTextureMode = "GRAY",

      text = {
        fontKey = nil,
        size = 12,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "LEFT",
        offX = 4,
        offY = 0,
      },
      timeText = {
        showCast = true,
        fontKey = nil,
        size = 12,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "RIGHT",
        offX = -4,
        offY = 0,
      },
    },

    target = {
      enabled = true,
      width = 220,
      height = 18,
      showIcon = true,
      borderSize = 1,
      attachToUF = true,
      point = "BOTTOM",
      relativePoint = "TOP",
      offsetX = 0,
      offsetY = 50,
      userMoved = false,
      texture = "Pleebar",
      useClassColor = false,
      color = COLORS.target,
      bgColor = COLORS.bg,
      showTotal = true,
      showSpark = true,
      reverseFill = false,
      timeToHold = 0.20,
      showChannelTicks = true,
      showDelayText = true,
      displayTarget = true,
      uninterruptShieldMode = "LEFT",
      uninterruptTextureMode = "GRAY",

      text = {
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "LEFT",
        offX = 6,
        offY = 0,
      },
      timeText = {
        showCast = true,
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "RIGHT",
        offX = -6,
        offY = 0,
      },
    },

    focus = {
      enabled = true,
      width = 200,
      height = 20,
      showIcon = true,
      borderSize = 1,
      attachToUF = false,
      point = "RIGHT",
      relativePoint = "LEFT",
      relativeTo = "PleebUI_UnitFrame_focus",
      offsetX = -10,
      offsetY = 0,
      userMoved = false,
      texture = "Pleebar",
      useClassColor = false,
      color = COLORS.focus,
      bgColor = COLORS.bg,
      showTotal = true,
      showSpark = true,
      reverseFill = false,
      timeToHold = 0.20,
      showChannelTicks = true,
      showDelayText = true,
      displayTarget = true,
      uninterruptShieldMode = "LEFT",
      uninterruptTextureMode = "GRAY",

      text = {
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "LEFT",
        offX = 6,
        offY = 0,
      },
      timeText = {
        showCast = true,
        fontKey = nil,
        size = 14,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "RIGHT",
        offX = -6,
        offY = 0,
      },
    },

    boss = {
      enabled = true,
      width = 250,
      height = 20,
      showIcon = true,
      borderSize = 1,
      attachToUF = true,
      point = "TOP",
      relativePoint = "BOTTOM",
      offsetX = 0,
      offsetY = -6,
      userMoved = false,
      texture = "Pleebar",
      color = COLORS.boss,
      bgColor = COLORS.bg,
      showTotal = false,
      showSpark = true,
      reverseFill = false,
      timeToHold = 0.20,
      showChannelTicks = true,
      showDelayText = true,
      uninterruptShieldMode = "LEFT",
      uninterruptTextureMode = "GRAY",

      text = {
        fontKey = nil,
        size = 12,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "LEFT",
        offX = 4,
        offY = 0,
      },
      timeText = {
        showCast = false,
        fontKey = nil,
        size = 12,
        flags = "OUTLINE",
        color = { 1, 1, 1, 1 },
        anchor = "RIGHT",
        offX = -4,
        offY = 0,
      },
    },
  },
}

CastBar.DefaultColors = COLORS
CastBar.defaults = defaults


ns.Pleebug:DropIn(CastBar, { name = "UnitFrames.CastBar.Defaults" })


