
-- File: PUI_UF_Defaults.lua
-- Purpose: Central UnitFrames defaults for profile, single units, grouped frames, auras, range, text, and media.


local ADDON_NAME, ns = ...

ns.UFDefaults = ns.UFDefaults or {}

local UFDefaults = ns.UFDefaults
local P = select(1, ns.Pleebug:DropIn(UFDefaults))

UFDefaults.Profile = {
  enabled      = true,
  hideBlizzard = true, 

  borderEdgeSize = 1,
  borderPlacement = "outside",

  media = {
    healthTexture = "Pleebar", -- LSM name
    powerTexture = "Pleebar", -- LSM name
  },

  colors = {
    useReactionForNPC = true,
    useClassForNames = false,
    nameText = { 1, 1, 1, 1 },
    deadText = { 0.7, 0.7, 0.7, 1 },
    healthMissing = { 0.2, 0.2, 0.2, 1 },
    healthIncomingPlayer = { 0.20, 0.85, 0.35, 0.55 },
    healthIncomingOther = { 0.35, 0.65, 1.00, 0.35 },
    healthAbsorb = { 0.50196081399918, 0.75294125080109, 1, 0.8 },
    healthHealAbsorb = { 0.50196078431373, 0.25098039215686, 1, 1 },
  },


  powerText = {
    enabled     = true,
    format      = "CUR", 
    displayMode = "CUR",  
  },

  range = {
    outOfRangeAlpha = 0.5,
  },


  enableMouseoverTooltips = true,
  enableMouseoverHighlight = true,
  healthPrediction = {
    incomingHeals = true,
    damageAbsorbs = true,
    healAbsorbs = true,
  },
  mouseoverHighlightMode = "BOTH",
  mouseoverHighlightStrength = 0.55,
  mouseoverHighlightBorderSize = 3,
  targetHighlightBorderSize = 3,

  -- Auras (buffs/debuffs)
  auras = {
    enabled = true,

    -- Debuffs
    showDebuffs = true,
    onlyPlayerDebuffs = false,
    hidePermanentDebuffs = false,
    debuffHideSated = true,
    debuffFilterMode = "BLIZZARD",

    -- Buffs
    showBuffs = false,
    onlyPlayerBuffs = false,
    hidePermanentBuffs = true,
    buffFilterMode = "BLIZZARD",

    iconSize = 18,
    debuffIconSize = 18,
    buffIconSize = 18,
    durationTextSize = 11,
    stackTextSize = 11,
    buffDurationTextSize = 11,
    buffDurationOutline = "OUTLINE",
    buffDurationAnchor = "TOPLEFT",
    buffDurationXOffset = 1,
    buffDurationYOffset = -1,
    buffStackTextSize = 11,
    buffStackOutline = "OUTLINE",
    buffStackAnchor = "BOTTOMRIGHT",
    buffStackXOffset = -1,
    buffStackYOffset = 1,
    debuffDurationTextSize = 11,
    debuffDurationOutline = "OUTLINE",
    debuffDurationAnchor = "TOPLEFT",
    debuffDurationXOffset = 1,
    debuffDurationYOffset = -1,
    debuffStackTextSize = 11,
    debuffStackOutline = "OUTLINE",
    debuffStackAnchor = "BOTTOMRIGHT",
    debuffStackXOffset = -1,
    debuffStackYOffset = 1,
    buffBorderSize = 0,
    debuffBorderSize = 1,
    buffBorderColor = { 0, 0, 0, 1 },
    debuffBorderColor = { 0, 0, 0, 1 },

    spacing = 2,
    maxIcons = 8,
    maxDuration = 300,
    useBlocklist = true,

    isAuraRaidInCombatPlayer = false,
    isAuraRaidPlayerDispellable = false,
    isAuraCrowdControl = false,
    isAuraRaid = false,

    -- Tooltips on hover
    tooltips = true,
    clickThrough = false,

    buffsPerRow = 8,
    buffsNumRows = 1,
    buffsAttachTo = "FRAME",
    buffsAnchorPoint = "TOPRIGHT",
    buffsGrowthX = "LEFT",
    buffsGrowthY = "DOWN",
    buffsSortMethod = "INDEX",
    buffsSortDirection = "ASCENDING",
    buffsXOffset = 0,
    buffsYOffset = -6,

    debuffsPerRow = 8,
    debuffsNumRows = 1,
    debuffsAttachTo = "FRAME",
    debuffsAnchorPoint = "BOTTOMLEFT",
    debuffsGrowthX = "RIGHT",
    debuffsGrowthY = "UP",
    debuffsSortMethod = "INDEX",
    debuffsSortDirection = "ASCENDING",
    debuffsXOffset = 0,
    debuffsYOffset = 6,
  },

  -- Global text / font config for all unit frames.

  -- Per-unit overrides live in units[unit].text.
  text = {
    -- LSM font key. If empty/nil, we fall back to Theme.fonts.body ("Use Global Font").
    font = "",

    -- Outline flag: "", "OUTLINE", "THICKOUTLINE", "MONOCHROMEOUTLINE"
    outline = "OUTLINE",

    -- Base sizes for the three text roles (player/target/most units).
    sizeName = 14,
    sizeHealth = 14,
    sizePower = 12,
    powerMode = "CUR",
    shortenValues = false,

    -- Default anchors for each text role.
    -- Valid: "LEFT", "CENTER", "RIGHT".
    anchorName = "LEFT",
    anchorHealth = "RIGHT",
    anchorPower = "RIGHT",

    -- Default offsets (in pixels) relative to the chosen anchor.
    -- Your request: no offsets - text anchored flush to bar edges.
    offsetNameX = 0,
    offsetNameY = 0,
    offsetHealthX = 0,
    offsetHealthY = 0,
    offsetPowerX = 0,
    offsetPowerY = 0,
    useNSRTNicknames = false,
  },

  units = {},
}


UFDefaults.Player = {
  player = {
    enabled = true,
    width = 200,
    height = 40,
    powerHeight = 8,
    showPower = true,
    portrait = {
      enabled = false,
      style = "2D",
      side = "LEFT",
      zoom = 0,
    },
    text = { healthMode = "CUR_PERCENT" },
    point = "CENTER",
    relativeTo = "UIParent",
    relativePoint = "CENTER",
    x = -275,
    y = -350,
    auras = {
      showBuffs = false,
      onlyPlayerBuffs = false,
      hidePermanentBuffs = true,
      buffFilterMode = "ALL",
      showDebuffs = false,
      onlyPlayerDebuffs = false,
      hidePermanentDebuffs = false,
      debuffFilterMode = "ALL",
      buffsAttachTo = "DEBUFFS",
      buffsAnchorPoint = "TOPLEFT",
      buffsGrowthX = "RIGHT",
      buffsGrowthY = "UP",
      buffsSortMethod = "TIME_REMAINING",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "TOPLEFT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "TIME_REMAINING",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },
  },
  pet = {
    enabled = true,
    width = 120,
    height = 25,
    powerHeight = 0,
    showPower = false,
    text = { healthMode = "PERCENT" },
    point = "TOP",
    relativeTo = "PleebUI_UnitFrame_player",
    relativePoint = "BOTTOM",
    x = 0,
    y = -20,
    auras = {
      showBuffs = false,
      onlyPlayerBuffs = false,
      hidePermanentBuffs = true,
      showDebuffs = true,
      onlyPlayerDebuffs = false,
      hidePermanentDebuffs = false,
      buffsPerRow = 7,
      buffsNumRows = 1,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "BOTTOMLEFT",
      buffsGrowthX = "RIGHT",
      buffsGrowthY = "UP",
      buffsSortMethod = "TIME_REMAINING",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,
      debuffsPerRow = 5,
      debuffsNumRows = 1,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "BOTTOMRIGHT",
      debuffsGrowthX = "LEFT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "TIME_REMAINING",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },
  },
}


UFDefaults.Target = {
  target = {
    enabled = true,
    width = 200,
    height = 40,
    powerHeight = 8,
    showPower = true,
    portrait = {
      enabled = false,
      style = "2D",
      side = "LEFT",
      width = 32,
      zoom = 0,
    },
    text = { healthMode = "CUR_PERCENT" },
    point = "CENTER",
    relativeTo = "UIParent",
    relativePoint = "CENTER",
    x = 275,
    y = -350,
    auras = {
      showBuffs = true,
      onlyPlayerBuffs = false,
      hidePermanentBuffs = true,
      buffFilterMode = "ALL",
      showDebuffs = true,
      onlyPlayerDebuffs = true,
      defaultDebuffsIncludeBossAuras = true,
      hidePermanentDebuffs = false,
      debuffFilterMode = "ALL",
      buffIconSize = 25,
      debuffIconSize = 25,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "TOPRIGHT",
      buffsRelativePoint = "BOTTOMRIGHT",
      buffsGrowthX = "LEFT",
      buffsGrowthY = "DOWN",
      buffsSortMethod = "TIME_REMAINING",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "BOTTOMLEFT",
      debuffsRelativePoint = "TOPLEFT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "TIME_REMAINING",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },
  },
  targettarget = {
    enabled = true,
    width = 120,
    height = 25,
    powerHeight = 0,
    showPower = false,
    text = { healthMode = "PERCENT" },
    point = "LEFT",
    relativeTo = "PleebUI_UnitFrame_target",
    relativePoint = "RIGHT",
    x = 12,
    y = 0,
    auras = {
      showBuffs = false,
      onlyPlayerBuffs = false,
      showDebuffs = false,
      onlyPlayerDebuffs = false,
    },
  },
}


UFDefaults.Focus = {
  focus = {
    enabled = true,
    width = 200,
    height = 30,
    powerHeight = 0,
    showPower = false,
    portrait = {
      enabled = false,
      style = "2D",
      side = "LEFT",
      zoom = 0,
    },
    text = { healthMode = "CUR_PERCENT" },
    point = "CENTER",
    relativeTo = "UIParent",
    relativePoint = "CENTER",
    x = 400,
    y = 200,
    auras = {
      showBuffs = true,
      onlyPlayerBuffs = false,
      hidePermanentBuffs = true,
      buffFilterMode = "ALL",
      showDebuffs = true,
      onlyPlayerDebuffs = true,
      defaultDebuffsIncludeBossAuras = true,
      hidePermanentDebuffs = false,
      debuffFilterMode = "ALL",
      buffIconSize = 25,
      debuffIconSize = 25,
      buffsPerRow = 7,
      buffsNumRows = 1,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "TOPRIGHT",
      buffsRelativePoint = "BOTTOMRIGHT",
      buffsGrowthX = "LEFT",
      buffsGrowthY = "DOWN",
      buffsSortMethod = "TIME_REMAINING",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,
      debuffsPerRow = 5,
      debuffsNumRows = 1,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "BOTTOMLEFT",
      debuffsRelativePoint = "TOPLEFT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "TIME_REMAINING",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },
  },
  focustarget = {
    enabled = true,
    width = 120,
    height = 25,
    powerHeight = 0,
    showPower = false,
    text = { healthMode = "PERCENT" },
    point = "LEFT",
    relativeTo = "PleebUI_UnitFrame_focus",
    relativePoint = "RIGHT",
    x = 12,
    y = 0,
    auras = {
      showBuffs = false,
      onlyPlayerBuffs = false,
      showDebuffs = false,
      onlyPlayerDebuffs = false,
    },
  },
}


UFDefaults.Boss = {
  boss = {
    width = 250,
    height = 42,
    spacing = 30,
    growthDirection = "DOWN",
    powerHeight = 8,
    showPower = true,
    portrait = {
      enabled = false,
      style = "2D",
      side = "LEFT",
      zoom = 0,
    },
    text = { healthMode = "CUR_PERCENT" },
    auras = {
      showBuffs = true,
      onlyPlayerBuffs = false,
      hidePermanentBuffs = false,
      buffFilterMode = "ALL",
      showDebuffs = true,
      onlyPlayerDebuffs = true,
      defaultDebuffsIncludeBossAuras = true,
      hidePermanentDebuffs = false,
      debuffFilterMode = "ALL",
      maxDuration = 0,
      iconSize = 22,
      buffIconSize = 22,
      debuffIconSize = 22,
      buffsPerRow = 3,
      buffsNumRows = 1,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "LEFT",
      buffsGrowthX = "RIGHT",
      buffsGrowthY = "UP",
      buffsSortMethod = "TIME_REMAINING",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 20,
      debuffsPerRow = 3,
      debuffsNumRows = 1,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "LEFT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "TIME_REMAINING",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = -3,
    },

  },
  boss1 = {
    enabled = true,
    point = "CENTER",
    relativeTo = "UIParent",
    relativePoint = "CENTER",
    x = 900,
    y = 250,
  },
  boss2 = {
    enabled = true,
    point = "TOP",
    relativeTo = "PleebUI_UnitFrame_boss1",
    relativePoint = "BOTTOM",
    x = 0,
    y = -30,
  },
  boss3 = {
    enabled = true,
    point = "TOP",
    relativeTo = "PleebUI_UnitFrame_boss2",
    relativePoint = "BOTTOM",
    x = 0,
    y = -30,
  },
  boss4 = {
    enabled = true,
    point = "TOP",
    relativeTo = "PleebUI_UnitFrame_boss3",
    relativePoint = "BOTTOM",
    x = 0,
    y = -30,
  },
  boss5 = {
    enabled = true,
    point = "TOP",
    relativeTo = "PleebUI_UnitFrame_boss4",
    relativePoint = "BOTTOM",
    x = 0,
    y = -30,
  },
}

UFDefaults.PartyRoleIcon = {
  roleIconSize = 17,
  roleIconPosition = "BOTTOM",
}

UFDefaults.RaidRoleIcon = {
  roleIconSize = 17,
  roleIconPosition = "TOPLEFT",
}

function UFDefaults.GetPartyDefaults()
  return {
  profile = {
    enabled = true,
    hideInRaid = true,

    width = 170,
    height = 36,
    powerHeight = 5,
    spacing = 8,

    point = "CENTER",
    relativeTo = "UIParent",
    relativePoint = "CENTER",
    x = 450,
    y = -120,

    orientation = "VERTICAL",
    growthY = "DOWN",
    sortOrder = "INDEX",
    sortDir = "ASC",
    roleSortOrder = "TANK,HEALER,DAMAGER,NONE",
    showPlayer = false,
    showSolo = false,
    showPower = true,
    portrait = {
      enabled = false,
      style = "2D",
      side = "LEFT",
      zoom = 0,
    },
    useClassColor = true,
    showRaidRoleStrip = true,
    raidRoleStripPosition = "TOPLEFT",
    raidRoleStripXOffset = 0,
    raidRoleStripYOffset = 0,
    raidRoleStripSize = 12,
    showLeader = true,
    showRaidAssistant = true,
    showMainTank = true,
    showMainAssist = true,
    showRoleIcon = true,
    roleIconSize = 17,
    roleIconPosition = "BOTTOM",
    roleIconXOffset = 0,
    roleIconYOffset = 0,
    showRaidTarget = true,
    raidTargetAnchorPoint = "TOP",
    raidTargetXOffset = 0,
    raidTargetYOffset = 0,
    raidTargetSize = 18,
    statusIconSize = 18,
    borderSize = 1,

    colors = {
      borderColor = { 0.10, 0.10, 0.10, 1.0 },
      healthBar = { 0.35, 0.35, 0.35, 1.0 },
      healthMissing = { 0.15, 0.15, 0.15, 0.95 },
      powerMissing = { 0.10, 0.10, 0.10, 0.95 },
      useClassForNames = false,
      nameText = { 1, 1, 1, 1 },
      healthText = { 1, 1, 1, 1 },
      powerText = { 1, 1, 1, 1 },
    },

    healthTexture = "Pleebar",
    powerTexture = "Pleebar",

    text = {
      font = "",
      sizeName = 12,
      sizeHealth = 11,
      sizePower = 10,
      outline = "OUTLINE",
      healthMode = "PERCENT",
      powerMode = "CUR",
      anchorName = "LEFT",
      anchorHealth = "RIGHT",
      anchorPower = "RIGHT",
      offsetNameX = 4,
      offsetNameY = 0,
      offsetHealthX = -4,
      offsetHealthY = 0,
      offsetPowerX = -2,
      offsetPowerY = 0,
    },

    auras = {
      enabled = true,

      showBuffs = true,
      showDebuffs = true,
      hidePermanentBuffs = true,
      hidePermanentDebuffs = false,
      buffHideRaidBuff = false,
      debuffHideSated = true,

      buffIsAuraRaid = false,
      buffIsAuraRaidPlayer = false,
      buffIsAuraRaidInCombat = false,
      buffIsAuraRaidInCombatPlayer = true,
      buffIsAuraCrowdControl = false,
      buffIsAuraCrowdControlPlayer = false,
      buffIsAuraPermanent = false,
      buffIsAuraPermanentPlayer = false,

      debuffIsAuraRaidPlayerDispellable = false,
      debuffIsAuraRaid = false,
      debuffIsAuraRaidInCombat = false,
      debuffIsAuraCrowdControl = false,
      debuffIsAuraPermanent = false,

      iconSize = 16,
      buffIconSize = 16,
      debuffIconSize = 16,

      durationTextSize = 10,
      stackTextSize = 10,
      buffDurationTextSize = 10,
      buffDurationOutline = "OUTLINE",
      buffDurationAnchor = "TOPLEFT",
      buffDurationXOffset = 1,
      buffDurationYOffset = -1,
      buffStackTextSize = 10,
      buffStackOutline = "OUTLINE",
      buffStackAnchor = "BOTTOMRIGHT",
      buffStackXOffset = -1,
      buffStackYOffset = 1,
      debuffDurationTextSize = 10,
      debuffDurationOutline = "OUTLINE",
      debuffDurationAnchor = "TOPLEFT",
      debuffDurationXOffset = 1,
      debuffDurationYOffset = -1,
      debuffStackTextSize = 10,
      debuffStackOutline = "OUTLINE",
      debuffStackAnchor = "BOTTOMRIGHT",
      debuffStackXOffset = -1,
      debuffStackYOffset = 1,
      disableSwipe = false,
      disableCountdownText = false,

      buffBorderSize = 0,
      debuffBorderSize = 1,
      dispelBorderSize = 2,
      buffBorderColor = { 0, 0, 0, 1 },
      debuffBorderColor = { 0, 0, 0, 1 },

      spacing = 2,
      maxIcons = 3,
      tooltips = true,
      buffTooltips = true,
      debuffTooltips = true,
      clickThrough = true,

      buffsPerRow = 3,
      buffsNumRows = 1,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "RIGHT",
      buffsRelativePoint = "LEFT",
      buffsGrowthX = "LEFT",
      buffsGrowthY = "DOWN",
      buffsSortMethod = "PLAYER",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,

      debuffsPerRow = 3,
      debuffsNumRows = 1,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "LEFT",
      debuffsRelativePoint = "RIGHT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "PLAYER",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },


    tracking = {
      enabled = false,
      tracks = {},
    },

    threatIndicator = {
      enabled = true,
      style = "FRAME_GLOW",
      borderSize = 3,
    },

    debuffHighlighting = "GLOW",

    debuffHighlight = {
      borderSize = 3,
      blizzardIndicator = false,
      blizzardIndicatorSize = 18,
      blizzardIndicatorPosition = "TOPRIGHT",
      blizzardIndicatorXOffset = 0,
      blizzardIndicatorYOffset = 0,
    },

    range = {
      enabled = true,
      outOfRangeAlpha = 0.45,
      updateInterval = 0.25,
    },

    partyPets = {
      enabled = true,
      trackAuras = false,
      width = 90,
      height = 16,
      powerHeight = 0,
      showPower = false,
      spacing = 2,
      anchorPoint = "TOP",
      relativePoint = "BOTTOM",
      x = 0,
      y = -2,
    },
  },
  }
end

function UFDefaults.GetRaidDefaults()
  return {
  profile = {
    enabled = true,
    hideBlizzard = true,

    width = 85,
    height = 54,
    powerHeight = 0,
    showPower = false,
    borderSize = 1,

    point = "BOTTOMLEFT",
    relativeTo = "UIParent",
    relativePoint = "BOTTOMLEFT",
    x = 4,
    y = 248,

    growthDirection = "RIGHT_DOWN",
    groupSortOrientation = "HORIZONTAL",
    lockMembersToGroup = true,
    moveGroupsSeparately = false,
    showGroupNumbers = true,
    groupBy = "GROUP",
    sortOrder = "INDEX",
    sortDir = "ASC",
    numGroups = 5,
    unitsPerColumn = 5,
    rowSpacing = 3,
    columnSpacing = 3,
    showPlayer = true,
    enableMainTankFrames = false,

    useClassColor = true,
    showRaidRoleStrip = true,
    raidRoleStripPosition = "TOPLEFT",
    raidRoleStripXOffset = 0,
    raidRoleStripYOffset = 0,
    raidRoleStripSize = 12,
    showLeader = true,
    showRaidAssistant = true,
    showMainTank = true,
    showMainAssist = true,
    showRoleIcon = true,
    roleIconSize = 17,
    roleIconPosition = "TOPLEFT",
    roleIconXOffset = 0,
    roleIconYOffset = 0,
    showRaidTarget = true,
    raidTargetAnchorPoint = "TOP",
    raidTargetXOffset = 0,
    raidTargetYOffset = 0,
    raidTargetSize = 18,
    statusIconSize = 18,

    colors = {
      borderColor = { 0.10, 0.10, 0.10, 1.0 },
      healthBar = { 0.35, 0.35, 0.35, 1.0 },
      healthMissing = { 0.15, 0.15, 0.15, 0.95 },
      powerMissing = { 0.10, 0.10, 0.10, 0.95 },
      useClassForNames = false,
      nameText = { 1, 1, 1, 1 },
      healthText = { 1, 1, 1, 1 },
      powerText = { 1, 1, 1, 1 },
    },

    healthTexture = "Pleebar",
    powerTexture = "Pleebar",

    text = {
      font = "",
      sizeName = 11,
      sizeHealth = 10,
      sizePower = 9,
      outline = "OUTLINE",
      healthMode = "PERCENT",
      powerMode = "HIDE",
      anchorName = "LEFT",
      anchorHealth = "BOTTOM",
      anchorPower = "BOTTOMRIGHT",
      offsetNameX = 4,
      offsetNameY = 0,
      offsetHealthX = 0,
      offsetHealthY = 2,
      offsetPowerX = -2,
      offsetPowerY = 2,
    },

    auras = {
      enabled = true,

      showBuffs = true,
      showDebuffs = true,
      hidePermanentBuffs = true,
      hidePermanentDebuffs = false,
      buffHideRaidBuff = false,
      debuffHideSated = true,

      buffIsAuraRaid = false,
      buffIsAuraRaidPlayer = false,
      buffIsAuraRaidInCombat = false,
      buffIsAuraRaidInCombatPlayer = true,
      buffIsAuraCrowdControl = false,
      buffIsAuraCrowdControlPlayer = false,
      buffIsAuraPermanent = false,
      buffIsAuraPermanentPlayer = false,

      debuffIsAuraRaidPlayerDispellable = false,
      debuffIsAuraRaid = false,
      debuffIsAuraRaidInCombat = false,
      debuffIsAuraCrowdControl = false,
      debuffIsAuraPermanent = false,

      iconSize = 20,
      buffIconSize = 20,
      debuffIconSize = 20,

      durationTextSize = 10,
      stackTextSize = 10,
      buffDurationTextSize = 10,
      buffDurationOutline = "OUTLINE",
      buffDurationAnchor = "TOPLEFT",
      buffDurationXOffset = 1,
      buffDurationYOffset = -1,
      buffStackTextSize = 10,
      buffStackOutline = "OUTLINE",
      buffStackAnchor = "BOTTOMRIGHT",
      buffStackXOffset = -1,
      buffStackYOffset = 1,
      debuffDurationTextSize = 10,
      debuffDurationOutline = "OUTLINE",
      debuffDurationAnchor = "TOPLEFT",
      debuffDurationXOffset = 1,
      debuffDurationYOffset = -1,
      debuffStackTextSize = 10,
      debuffStackOutline = "OUTLINE",
      debuffStackAnchor = "BOTTOMRIGHT",
      debuffStackXOffset = -1,
      debuffStackYOffset = 1,
      disableSwipe = false,
      disableCountdownText = false,

      buffBorderSize = 0,
      debuffBorderSize = 1,
      dispelBorderSize = 2,
      buffBorderColor = { 0, 0, 0, 1 },
      debuffBorderColor = { 0, 0, 0, 1 },

      spacing = 2,
      maxIcons = 3,
      tooltips = true,
      buffTooltips = true,
      debuffTooltips = true,
      clickThrough = true,

      buffsPerRow = 3,
      buffsNumRows = 1,
      buffsAttachTo = "FRAME",
      buffsAnchorPoint = "TOPLEFT",
      buffsRelativePoint = "TOPLEFT",
      buffsGrowthX = "RIGHT",
      buffsGrowthY = "DOWN",
      buffsSortMethod = "PLAYER",
      buffsSortDirection = "DESCENDING",
      buffsXOffset = 0,
      buffsYOffset = 0,

      debuffsPerRow = 3,
      debuffsNumRows = 1,
      debuffsAttachTo = "FRAME",
      debuffsAnchorPoint = "BOTTOMLEFT",
      debuffsRelativePoint = "BOTTOMLEFT",
      debuffsGrowthX = "RIGHT",
      debuffsGrowthY = "UP",
      debuffsSortMethod = "PLAYER",
      debuffsSortDirection = "DESCENDING",
      debuffsXOffset = 0,
      debuffsYOffset = 0,
    },

    tracking = {
      enabled = false,
      tracks = {},
    },

    threatIndicator = {
      enabled = true,
      style = "FRAME_GLOW",
      borderSize = 3,
    },

    debuffHighlighting = "GLOW",

    debuffHighlight = {
      borderSize = 3,
      blizzardIndicator = false,
      blizzardIndicatorSize = 18,
      blizzardIndicatorPosition = "TOPRIGHT",
      blizzardIndicatorXOffset = 0,
      blizzardIndicatorYOffset = 0,
    },

    range = {
      enabled = true,
      outOfRangeAlpha = 0.45,
      updateInterval = 0.25,
    },
  },
  }
end

UFDefaults.GetPartyDefaults = P:Def("UFDefaults:GetPartyDefaults", UFDefaults.GetPartyDefaults)
UFDefaults.GetRaidDefaults = P:Def("UFDefaults:GetRaidDefaults", UFDefaults.GetRaidDefaults)
